In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('/content/diabetes_dataset.csv')

In [ ]:
df.isnull().sum()

patient_id                    0
age                           0
gender                        0
pregnancies                   0
bmi                        2250
skin_thickness_mm             0
sbp_mmhg                      0
dbp_mmhg                      0
glucose_mg_dl                 0
fasting_glucose_mg_dl         0
ogtt_2hr_mg_dl                0
hba1c_pct                     0
insulin_mu_l               2250
ldl_mg_dl                     0
hdl_mg_dl                     0
triglycerides_mg_dl           0
creatinine_mg_dl              0
physical_activity             0
smoking_status                0
family_history_diabetes       0
hypertension                  0
diagnosis                     0
diagnosis_code                0
dtype: int64

In [ ]:
handling_null = pd.DataFrame()

In [ ]:
handling_null['bmi'] = df['bmi'].copy()

In [ ]:
handling_null['insulin_mu_l'] = df['insulin_mu_l'].copy()

In [ ]:
handling_null

        bmi  insulin_mu_l
0      36.2           8.6
1      15.0          17.2
2      25.7          10.0
3      27.7           5.6
4      28.1          24.1
...     ...           ...
14995  33.2         124.2
14996   NaN           NaN
14997  22.6          62.8
14998  28.8           NaN
14999  23.7         243.6

[15000 rows x 2 columns]

In [ ]:
for i in handling_null.columns:
  handling_null[i+'mean'] = handling_null[i].fillna(handling_null[i].mean())
  handling_null[i+'median'] = handling_null[i].fillna(handling_null[i].median())
  handling_null[i+'mode'] = handling_null[i].fillna(handling_null[i].mode()[0])

In [ ]:
handling_null.sample(20)

,bmi,insulin_mu_l,bmimean,bmimedian,bmimode,insulin_mu_lmean,insulin_mu_lmedian,insulin_mu_lmode
5283,18.1,28.2,18.10000,18.1,18.1,28.200000,28.2,28.2
825,31.4,23.5,31.40000,31.4,31.4,23.500000,23.5,23.5
5273,32.1,47.3,32.10000,32.1,32.1,47.300000,47.3,47.3
8973,32.7,2.0,32.70000,32.7,32.7,2.000000,2.0,2.0
4055,24.3,23.9,24.30000,24.3,24.3,23.900000,23.9,23.9
3528,21.8,19.9,21.80000,21.8,21.8,19.900000,19.9,19.9
1851,26.6,212.4,26.60000,26.6,26.6,212.400000,212.4,212.4
14476,41.4,2.0,41.40000,41.4,41.4,2.000000,2.0,2.0
1782,25.8,379.4,25.80000,25.8,25.8,379.400000,379.4,379.4
2711,24.1,2.0,24.10000,24.1,24.1,2.000000,2.0,2.0
5036,29.7,NaN,29.70000,29.7,29.7,85.406267,59.7,2.0
819,36.8,120.4,36.80000,36.8,36.8,120.400000,120.4,120.4
729,30.9,NaN,30.90000,30.9,30.9,85.406267,59.7,2.0
6334,26.1,98.0,26.10000,26.1,26.1,98.000000,98.0,98.0
2544,36.3,NaN,36.30000,36.3,36.3,85.406267,59.7,2.0
2762,NaN,69.2,28.20098,28.1,15.0,69.200000,69.2,69.2
13791,NaN,206.9,28.20098,28.1,15.0,206.900000,206.9,206.9
12841,34.5,51.8,34.50000,34.5,34.5,51.800000,51.8,51.8
55,29.7,101.3,29.70000,29.7,29.7,101.300000,101.3,101.3
3180,25.2,52.6,25.20000,25.2,25.2,52.600000,52.6,52.6

In [ ]:
handling_null['bmi_ran'] = handling_null['bmi']
s = handling_null['bmi'].dropna().sample(handling_null['bmi'].isnull().sum())
s.index = handling_null[handling_null['bmi'].isnull()].index
handling_null.loc[handling_null['bmi'].isnull(), 'bmi_ran'] = s

In [ ]:
handling_null['insulin_mu_l_ran'] = handling_null['insulin_mu_l']
s = handling_null['insulin_mu_l'].dropna().sample(handling_null['insulin_mu_l'].isnull().sum())
s.index = handling_null[handling_null['insulin_mu_l'].isnull()].index
handling_null.loc[handling_null['insulin_mu_l'].isnull(), 'insulin_mu_l_ran'] = s

In [ ]:
handling_null

,bmi,insulin_mu_l,bmimean,bmimedian,bmimode,insulin_mu_lmean,insulin_mu_lmedian,insulin_mu_lmode,bmi_ran,insulin_mu_l_ran
0,36.2,8.6,36.20000,36.2,36.2,8.600000,8.6,8.6,36.2,8.6
1,15.0,17.2,15.00000,15.0,15.0,17.200000,17.2,17.2,15.0,17.2
2,25.7,10.0,25.70000,25.7,25.7,10.000000,10.0,10.0,25.7,10.0
3,27.7,5.6,27.70000,27.7,27.7,5.600000,5.6,5.6,27.7,5.6
4,28.1,24.1,28.10000,28.1,28.1,24.100000,24.1,24.1,28.1,24.1
...,...,...,...,...,...,...,...,...,...,...
14995,33.2,124.2,33.20000,33.2,33.2,124.200000,124.2,124.2,33.2,124.2
14996,NaN,NaN,28.20098,28.1,15.0,85.406267,59.7,2.0,41.6,130.0
14997,22.6,62.8,22.60000,22.6,22.6,62.800000,62.8,62.8,22.6,62.8
14998,28.8,NaN,28.80000,28.8,28.8,85.406267,59.7,2.0,28.8,12.3
14999,23.7,243.6,23.70000,23.7,23.7,243.600000,243.6,243.6,23.7,243.6

In [ ]:
for i in handling_null.columns:
  print(f'{i} -> {handling_null[i].std()}')

bmi -> 6.780691361132524
insulin_mu_l -> 84.71169433839935
bmimean -> 6.251451769492327
bmimedian -> 6.25155576120992
bmimode -> 7.829497474781222
insulin_mu_lmean -> 78.09986375490092
insulin_mu_lmedian -> 78.63744581571235
insulin_mu_lmode -> 83.58597389412166
bmi_ran -> 6.778804340873211
insulin_mu_l_ran -> 84.15075272941934

In [ ]:
import sklearn
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
scale_cols = [
    'glucose_mg_dl',
    'fasting_glucose_mg_dl',
    'ogtt_2hr_mg_dl',
    'hba1c_pct',
    'ldl_mg_dl',
    'hdl_mg_dl',
    'sbp_mmhg',
    'dbp_mmhg',
    'bmi_ran',
    'skin_thickness_mm'
]